accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

mlb_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('info/', include('players_and_teams.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

players_and_teams/urls.py
from django.urls import path
from . import views

app_name = 'players_and_teams'

urlpatterns = [
    path('', views.player_list, name='player_list'),
    path('new_player', views.new_player, name='new_player'),
    path('<int:player_id>', views.player_detail, name='player_detail'),
    path('<int:player_id>/edit', views.edit_player, name='edit_player'),
    path('<int:player_id>/delete', views.delete_player, name='delete_player'),
    path('new_team', views.new_team, name='new_team'),
    path('edit_team/<int:team_id>/edit', views.edit_team, name='edit_team'),
    path('delete_team/<int:team_id>/delete', views.delete_team, name='delete_team'),
    path('news', views.news_detail, name='news_detail'),
]

accounts/models.py
from django.db import models

# Create your models here.

players_and_teams/models.py
from django.db import models
from django.contrib.auth.models import User

class Player(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='players')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Team(models.Model):
    city = models.CharField(max_length=50)
    nickname = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='teams')

    def __str__(self):
        return f"{self.city} {self.nickname}"

players_and_teams/forms.py
from django import forms
from .models import Player, Team

class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = ('first_name', 'last_name')

class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ('city', 'nickname')

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

players_and_teams/views.py
from django.shortcuts import render, redirect, HttpResponse
import requests
from .models import Player, Team
from .forms import PlayerForm, TeamForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


def get_player(player_id):
    return Player.objects.get(id=player_id)

def get_team(team_id):
    return Team.objects.get(id=team_id)

@login_required
def player_list(request):
    players = Player.objects.filter(user=request.user)
    teams = Team.objects.filter(user=request.user)
    return render(request, 'players/player_team_list.html', {'players': players, 'teams': teams})

def player_detail(request, player_id):
    player = get_player(player_id)
    name_for_search = generate_search_name(player.last_name)
    r = requests.get(name_for_search)
    response = r.json()
    content = {
        'team_full': response['search_player_all']['queryResults']['row']['team_full'],
        'position': response['search_player_all']['queryResults']['row']['position'],
        'bats': response['search_player_all']['queryResults']['row']['bats'],
        'throws': response['search_player_all']['queryResults']['row']['throws'],
        'birth_country': response['search_player_all']['queryResults']['row']['birth_country'],
        'birth_date': response['search_player_all']['queryResults']['row']['birth_date'],
        'height_feet': response['search_player_all']['queryResults']['row']['height_feet'],
        'height_inches': response['search_player_all']['queryResults']['row']['height_inches'],
        'player': player
    }
    return render(request, 'players/player_detail.html', content)

def new_player(request):
    if request.method == "POST":
        form = PlayerForm(request.POST)
        if form.is_valid():
            player = form.save(commit=False)
            player.user = request.user
            player.save()
            return (player_list(request))
    else:
        form = PlayerForm()
    return render(request, 'players/player_form.html', {'form': form, 'type_of_request': 'New'}) 

def edit_player(request, player_id):
    player = get_player(player_id)
    if request.method == "POST":
        form = PlayerForm(request.POST, instance=player)
        if form.is_valid():
            player = form.save(commit=False)
            player.user = request.user
            player.save()
            return player_list(request)
    else:
        form = PlayerForm(instance=player)
    return render(request, 'players/player_form.html', {'form': form, 'type_of_request': 'Edit'})

def delete_player(request, player_id):
    if request.method == "POST":
        player = get_player(player_id)
        player.delete()
    return player_list(request)

def new_team(request):
    if request.method == "POST":
        form = TeamForm(request.POST)
        if form.is_valid():
            team = form.save(commit=False)
            team.user = request.user
            team.save()
            return (player_list(request))
    else:
        form = TeamForm()
    return render(request, 'teams/team_form.html', {'form': form, 'type_of_request': 'New'})

def edit_team(request, team_id):
    team = get_team(team_id)
    if request.method == "POST":
        form = TeamForm(request.POST, instance=team)
        if form.is_valid():
            team = form.save(commit=False)
            team.user = request.user
            team.save()
            return player_list(request)
    else:
        form = TeamForm(instance=team)
    return render(request, 'teams/team_form.html', {'form': form, 'type_of_request': 'Edit'})

def delete_team(request, team_id):
    if request.method == "POST":
        team = get_team(team_id)
        team.delete()
    return player_list(request)

def generate_search_name(last_name):
    return f"http://lookup-service-prod.mlb.com/json/named.search_player_all.bam?sport_code='mlb'&active_sw='Y'&name_part='{ last_name }%25'"

def news_creater(news):
    modified_news = news.replace(' ', '%20')
    news_api = "72c55bbd64484a56a24f37a30f2ea656"
    return f"https://newsapi.org/v2/everything?q={modified_news}&from=2021-04-15&sortBy=popularity&language=en&apiKey={news_api}"

@login_required
def news_detail(request):
    if request.method == "GET":
        query = request.GET.get('q')
        if query:
            response = requests.get(news_creater(query))
            try:
                if response.json()['status'] == 'ok':
                    json_data=response.json()['articles'][0:10]
                    article_list = []
                    for article in json_data:
                        current_article = {'title': article['title'], 'description':article ['description'], 'url': article['url']}
                        article_list.append(current_article)
                    return render(request, 'players/news_detail.html', {'term': query,    'articles':article_list})
                    
            except Exception as e:
                print(e)
                return HttpResponse(f"No results were found for {query}")

players_and_teams/templates/players/player_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{player.first_name}} {{player.last_name}}</h1>
<p>Team: {{ team_full }}</p>
<p>Postion: {{ position }}</p>
<p>Bats: {{ bats }}</p>
<p>Throws: {{ throws }}</p>
<p>Birth Country: {{ birth_country }}</p>
<p>Date of Birth: {{ birth_date }}</p>
<p>Height: {{ height_feet }} feet {{ height_inches }} inches</p>
<br>
<a href="{% url 'edit_player' player_id=player.id %}"> Edit Player</a>
<br>
<br>
<form name="delete_player" method="POST" action="{% url 'delete_player' player_id=player.id %}">
    {% csrf_token %}
    <input type="submit" value="Delete Player" />
  </form>
<br>
<h1>Search</h1>
<p>Enter a Subject to Search for Articles</p>
<form type="get" action="{% url 'news_detail' %}" accept-charset="utf-8">
    <input type="search" id="q" name="q" placeholder="Search..."/>
    <button type="submit">Submit</button>
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Major Leageue Baseball App</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'players_and_teams:player_list' %}" aria-current="page">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'logout' %}" tabindex="-1" aria-current="page">Logout</a>
          </li>
        </ul>
        <form class="d-flex" type="get" action="{% url 'players_and_teams:news_detail' %}" accept-charset="utf-8">
          <input class="form-control me-2" type="search" id="q" name="q" placeholder="Search News" aria-label="Search">
          <button class="btn btn-light" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  <br>
<div class="container">
  {% block content %}
  {% endblock %}
</div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
  <div class="home_container">
    <h1 class="home_greeting display-4">Hi {{ user.username }}!</h1>
    <br>
    <p><a class="player_list_home" style="color: blue;" href="{% url 'players_and_teams:player_list' %}">Favorite Players and Teams</a></p>
    <img src="{% static 'media/fisheye_stadium.jpg' %}" alt="Baseball Stadium" width="100%" height="50%">
    </div>
  {% else %}
    <div class="home_not_login">
    <p class="not_login_warn display-4">You are not logged in!</p>
    <img src="{% static 'media/stadium.jpg' %}" alt="Dodger Stadium" width="100%" height="50%">
  </div>
  
  {% endif %}
{% endblock %}

templates/players/news_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="news_detail_container">
<h1 class="news_header">News For {{ term }}:</h1>

{% for article in articles %}
<div class="news_headlines_title">
<a class="news_headlines" href = "{{ article.url }}">{{ article.title }}</a></div>
<p class="article" >{{ article.description }}</p>
<br>
{% endfor %}
</div>
{% endblock %}

templates/players/player_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="player_container">
<h1 style="color:blue">{{player.first_name}} {{player.last_name}}</h1>
<table class="table table-success">
  <tbody>
    <tr>
      <th scope="row">Team</th>
      <td>{{ team_full }}</td>
    </tr>
    <tr>
      <th scope="row">Position</th>
      <td>{{ position }}</td>
    </tr>
    <tr>
      <th scope="row">Bats</th>
      <td colspan="2">{{ bats }}</td>
    </tr>
    <tr>
      <th scope="row">Throws</th>
      <td colspan="2">{{ throws }}</td>
    </tr>
    <tr>
      <th scope="row">Birth Country</th>
      <td colspan="2">{{ birth_country }}</td>
    </tr>
    <tr>
      <th scope="row">Date of Birth</th>
      <td colspan="2">{{ birth_date }}</td>
    </tr>
    <tr>
      <th scope="row">Height</th>
      <td colspan="2">{{ height_feet }} feet {{ height_inches }}  inches</td>
    </tr>
  </tbody>
</table>
<br>
<a class="edit_player"  style="color:blue" href="{% url 'players_and_teams:edit_player' player_id=player.id %}"> Edit Player</a>
<br>
<br>
<form name="delete_player" method="POST" action="{% url 'players_and_teams:delete_player' player_id=player.id %}">
    {% csrf_token %}
    <input class="delete_player btn-primary" type="submit" value="Delete Player" />
  </form>
</div>
{% endblock %}

templates/players/player_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="player_form_container">
<h2>{{ type_of_request }} Player</h2>
<form method="POST">{% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>
</div>
{% endblock %}

templates/players/player_team_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="player_team_list_container">
<h1 class="display-4">Favorite Players and Teams for User {{user.username}}:</h1>
  <h1 style="color: red;">Favorite Players</h1>
  <div class="row justify-content-center">
    <div class="col-auto">
  <table class="table table-success table-striped" id="player_table">
    <thead>
      <tr>
        <th> </th>
        <th scope="col">Player Name</th>
      </tr>
    </thead>
    {% for player in players %}
    <tbody>
      <tr>
        <td style="color: blue;"><b>--></b></td>
        <td><a  class="player_detail" href="{% url 'players_and_teams:player_detail' player_id=player.id %}"><h4>{{player.first_name}} {{player.last_name}}</h4></a></td>
      </tr>
    </tbody>
  </div>
  </div>
    {% endfor %}
  </table>
  <br>
  <a class="new_player" style="color: blue;" href="{% url 'players_and_teams:new_player' %}">Enter A New Player</a>
  <br>
  <h1 style="color:blue">Favorite Teams</h1>
  <table class="table table-success table-striped">
    <thead>
      <tr>
        <th> </th>
        <th scope="col">Team Name</th>
        <th> </th>
        <th> </th>
      </tr>
    </thead>
    {% for team in teams %}
    <tbody>
      <tr>
        <td style="color: blue;"><b>--></b></td>
        <td><a class="team_detail_list" href="http://www.mlb.com/{{ team.nickname }}"><h4>{{team.city}} {{team.nickname}}</h4></a></td>
        <td><a class="edit_team" style="color: blue;" href="{% url 'players_and_teams:edit_team' team_id=team.id %}"> Edit Team</a></td>
        <td><form name="delete_team" method="POST" action="{% url 'players_and_teams:delete_team' team_id=team.id %}">
          {% csrf_token %}
          <input class="btn btn-primary" type="submit" value="Delete Team" />
        </form></td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
  <br>
    <a class="enter_team" style="color: blue;" href="{% url 'players_and_teams:new_team' %}">Enter A New Team</a>
  </div>
{% endblock %}

templates/teams/team_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="team_form_container">
<h2>{{ type_of_request }} Team</h2>
<form method="POST">{% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>
</div>
{% endblock %}